version: '3.8'
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: ipond-timescaledb
    restart: unless-stopped
    environment:
      POSTGRES_USER: soletronix
      POSTGRES_PASSWORD: Soletronix-database2026
      POSTGRES_DB: ipond
    volumes:
      - /mnt/ipond-data/timescaledb:/var/lib/postgresql/data
    ports:
      - "5432:5432"
